# Generated by Django 5.2.8 on 2025-11-08 21:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_key', models.CharField(max_length=500, unique=True, verbose_name='S3 Key')),
                ('original_name', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('content_type', models.CharField(max_length=100, verbose_name='Content Type')),
                ('file_size', models.BigIntegerField(verbose_name='파일 크기 (bytes)')),
                ('url', models.URLField(verbose_name='파일 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '에셋',
                'verbose_name_plural': '에셋',
                'db_table': 'assets',
                'ordering': ['-created_at'],
            },
        ),
    ]
