# Generated by Django 5.2.8 on 2025-11-08 21:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='폴더 이름')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='폴더 색상')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_folders', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '채팅방 폴더',
                'verbose_name_plural': '채팅방 폴더',
                'db_table': 'chat_folders',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('direct', '1:1 채팅'), ('group', '그룹 채팅')], max_length=10, verbose_name='채팅방 타입')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='채팅방 이름')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rooms', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '채팅방',
                'verbose_name_plural': '채팅방',
                'db_table': 'chat_rooms',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatFolderRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='chat.chatfolder', verbose_name='폴더')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='chat.chatroom', verbose_name='채팅방')),
            ],
            options={
                'verbose_name': '폴더-채팅방',
                'verbose_name_plural': '폴더-채팅방',
                'db_table': 'chat_folder_rooms',
                'ordering': ['order', 'created_at'],
                'unique_together': {('folder', 'room')},
            },
        ),
        migrations.CreateModel(
            name='ChatRoomMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', '방장'), ('admin', '관리자'), ('member', '멤버')], default='member', max_length=10, verbose_name='역할')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='닉네임')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 읽은 시간')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.chatroom', verbose_name='채팅방')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_memberships', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '채팅방 멤버',
                'verbose_name_plural': '채팅방 멤버',
                'db_table': 'chat_room_members',
                'ordering': ['-joined_at'],
                'unique_together': {('room', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', '텍스트'), ('image', '이미지'), ('file', '파일'), ('system', '시스템 메시지')], default='text', max_length=10, verbose_name='메시지 타입')),
                ('content', models.TextField(verbose_name='메시지 내용 (암호화된 내용)')),
                ('encrypted_content', models.TextField(blank=True, null=True, verbose_name='암호화된 원본 내용')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.asset', verbose_name='첨부 파일')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message', verbose_name='답장 대상')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='채팅방')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='발신자')),
            ],
            options={
                'verbose_name': '메시지',
                'verbose_name_plural': '메시지',
                'db_table': 'messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['room', '-created_at'], name='messages_room_id_9d87cc_idx'), models.Index(fields=['sender', '-created_at'], name='messages_sender__7375e3_idx')],
            },
        ),
    ]
