# Generated by Django 5.2.8 on 2025-11-08 21:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChatInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '대기중'), ('accepted', '수락됨'), ('rejected', '거절됨')], default='pending', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL, verbose_name='초대받은 사람')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='초대자')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='chat.chatroom', verbose_name='채팅방')),
            ],
            options={
                'verbose_name': '그룹챗 초대',
                'verbose_name_plural': '그룹챗 초대',
                'db_table': 'group_chat_invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invitee', 'status'], name='group_chat__invitee_9701a3_idx'), models.Index(fields=['room', 'status'], name='group_chat__room_id_4f0367_idx')],
                'unique_together': {('room', 'invitee')},
            },
        ),
    ]
