# Generated by Django 5.2.8 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_groupchatinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encrypted_session_key',
            field=models.TextField(blank=True, null=True, verbose_name='암호화된 세션 키 (RSA 암호화)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='메시지 내용 (그룹 채팅용 평문)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='encrypted_content',
            field=models.TextField(blank=True, null=True, verbose_name='암호화된 메시지 내용 (AES 암호화)'),
        ),
    ]

