# Generated by Django 5.2.8 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_add_encrypted_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='self_encrypted_session_key',
            field=models.TextField(blank=True, null=True, verbose_name='자기 암호화된 세션 키 (RSA 암호화, 내 공개키로 암호화)'),
        ),
    ]

