# Generated by Django 5.2.8 on 2025-11-24 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_directchatinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='directchatinvitation',
            new_name='direct_chat_invitee_89226e_idx',
            old_name='direct_chat_invitee_status_idx',
        ),
        migrations.RenameIndex(
            model_name='directchatinvitation',
            new_name='direct_chat_inviter_ac2d91_idx',
            old_name='direct_chat_inviter_invitee_status_idx',
        ),
        migrations.AlterField(
            model_name='groupchatinvitation',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_group_invitations', to=settings.AUTH_USER_MODEL, verbose_name='초대받은 사람'),
        ),
        migrations.AlterField(
            model_name='groupchatinvitation',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_group_invitations', to=settings.AUTH_USER_MODEL, verbose_name='초대자'),
        ),
        migrations.AlterField(
            model_name='groupchatinvitation',
            name='status',
            field=models.CharField(choices=[('pending', '대기중'), ('accepted', '수락됨'), ('rejected', '거절됨'), ('cancelled', '취소됨')], default='pending', max_length=10, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='message',
            name='encrypted_session_key',
            field=models.TextField(blank=True, null=True, verbose_name='암호화된 세션 키 (RSA 암호화, 상대방 공개키로 암호화)'),
        ),
    ]
