# Generated by Django 5.2.8 on 2025-11-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_direct_chat_invitee_status_idx_direct_chat_invitee_89226e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatfolder',
            name='icon',
            field=models.CharField(default='folder.fill', max_length=50, verbose_name='폴더 아이콘'),
        ),
    ]
