# Generated by Django 5.2.8 on 2025-11-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatfolder_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='메시지 내용 (그룹 채팅용 평문)'),
        ),
    ]
