# Generated by Django 5.2.8 on 2025-11-08 21:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='사용자 ID')),
                ('phone_number', models.CharField(max_length=500, unique=True, verbose_name='전화번호 (암호화)')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('profile_image', models.URLField(blank=True, null=True, verbose_name='프로필 사진 URL')),
                ('public_key', models.TextField(blank=True, null=True, verbose_name='E2EE 공개키')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_key', models.CharField(max_length=500, unique=True, verbose_name='S3 Key')),
                ('original_name', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('content_type', models.CharField(max_length=100, verbose_name='Content Type')),
                ('file_size', models.BigIntegerField(verbose_name='파일 크기 (bytes)')),
                ('url', models.URLField(verbose_name='파일 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '에셋',
                'verbose_name_plural': '에셋',
                'db_table': 'assets',
                'ordering': ['-created_at'],
            },
        ),
    ]
