# Generated by Django 5.2.8 on 2025-11-20 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdevice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userdevice',
            new_name='user_device_user_id_3c1001_idx',
            old_name='user_device_user_id_is_primary_idx',
        ),
        migrations.RenameIndex(
            model_name='userdevice',
            new_name='user_device_device__d2dc6a_idx',
            old_name='user_device_device_fingerprint_idx',
        ),
    ]
